plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/LineLength:
  Max: 180
  Exclude:
    - lib/easy_talk/configuration.rb
    - spec/**/*

Style/StringLiterals:
  Enabled: false

Metrics/ClassLength:
  Max: 240

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ModuleLength:
  Max: 150

Metrics/BlockNesting:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/EndAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedDescription:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 10

RSpec/SpecFilePathFormat:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
